export const GET_COURSES_REQUEST_HOME = "GET_COURSES_REQUEST_HOME";
export const GET_COURSES_SUCCESS_HOME = "GET_COURSES_SUCCESS_HOME";
export const GET_COURSES_FAIL_HOME = "GET_COURSES_FAIL_HOME";

export const GET_COURSE_INFO_REQUEST = "GET_COURSE_INFO_REQUEST";
export const GET_COURSE_INFO_SUCCESS = "GET_COURSE_INFO_SUCCESS";
export const GET_COURSE_INFO_FAIL = "GET_COURSE_INFO_FAIL";

export const GET_COURSE_REVIEWS_REQUEST = "GET_COURSE_REVIEWS_REQUEST";
export const GET_COURSE_REVIEWS_SUCCESS = "GET_COURSE_REVIEWS_SUCCESS";
export const GET_COURSE_REVIEWS_FAIL = "GET_COURSE_REVIEWS_FAIL";
