export const GET_COURSES_REQUEST_HOME = "GET_COURSES_REQUEST_HOME";
export const GET_COURSES_SUCCESS_HOME = "GET_COURSES_SUCCESS_HOME";
export const GET_COURSES_FAIL_HOME = "GET_COURSES_FAIL_HOME";

export const GET_COURSE_INFO_REQUEST = "GET_COURSE_INFO_REQUEST";
export const GET_COURSE_INFO_SUCCESS = "GET_COURSE_INFO_SUCCESS";
export const GET_COURSE_INFO_FAIL = "GET_COURSE_INFO_FAIL";

export const GET_COURSE_REVIEWS_REQUEST = "GET_COURSE_REVIEWS_REQUEST";
export const GET_COURSE_REVIEWS_SUCCESS = "GET_COURSE_REVIEWS_SUCCESS";
export const GET_COURSE_REVIEWS_FAIL = "GET_COURSE_REVIEWS_FAIL";

export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAIL = "ENROLL_COURSE_FAIL";
export const ENROLL_COURSE_CLEAR = "ENROLL_COURSE_CLEAR";

export const GET_ENROLLED_COURSES_REQUEST = "GET_ENROLLED_COURSES_REQUEST";
export const GET_ENROLLED_COURSES_SUCCESS = "GET_ENROLLED_COURSES_SUCCESS";
export const GET_ENROLLED_COURSES_FAIL = "GET_ENROLLED_COURSES_FAIL";

export const GET_CREATED_COURSES_REQUEST = "GET_CREATED_COURSES_REQUEST";
export const GET_CREATED_COURSES_SUCCESS = "GET_CREATED_COURSES_SUCCESS";
export const GET_CREATED_COURSES_FAIL = "GET_CREATED_COURSES_FAIL";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";

export const SEARCH_COURSE_REQUEST = "SEARCH_COURSE_REQUEST";
export const SEARCH_COURSE_SUCCESS = "SEARCH_COURSE_SUCCESS";
export const SEARCH_COURSE_FAIL = "SEARCH_COURSE_FAIL";
