export const GET_COURSE_LESSONS_REQUEST = "GET_COURSE_LESSONS_REQUEST";
export const GET_COURSE_LESSONS_SUCCESS = "GET_COURSE_LESSONS_SUCCESS";
export const GET_COURSE_LESSONS_FAIL = "GET_COURSE_LESSONS_FAIL";
