export const GET_COURSE_LESSONS_REQUEST = "GET_COURSE_LESSONS_REQUEST";
export const GET_COURSE_LESSONS_SUCCESS = "GET_COURSE_LESSONS_SUCCESS";
export const GET_COURSE_LESSONS_FAIL = "GET_COURSE_LESSONS_FAIL";

export const GET_LESSON_INFO_REQUEST = "GET_LESSON_INFO_REQUEST";
export const GET_LESSON_INFO_SUCCESS = "GET_LESSON_INFO_SUCCESS";
export const GET_LESSON_INFO_FAIL = "GET_LESSON_INFO_FAIL";

export const ADD_LESSON_REQUEST = "ADD_LESSON_REQUEST";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";
export const ADD_LESSON_FAIL = "ADD_LESSON_FAIL";
export const ADD_LESSON_RESET = "ADD_LESSON_RESET";
