export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCSSES = "USER_SIGNIN_SUCSSES";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCSSES = "USER_SIGNUP_SUCSSES";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
